### ISSUE TITLE
Please make sure you always ...

### ISSUE THREAD

**Issue by AaronGulman** [RatnadeepRoy01/Resume-Maker#1]
Hi,
I am just here to highlight a couple of very important things.:

While it might not immediately jeopardize the safety of your project, it's very important to adopt best practices for handling secrets and sensitive data . So please remember that `.env`(s) are not there to be committed . 

If you are new maybe you could take on a task of learning how to delete your previous commits? 

Good job btw and good luck with everything !

**Comment by RatnadeepRoy01** [comment]
Hi Aaron,
Thank you for highlighting the vulnerability. I have removed the .env file
as per your suggestion. I appreciate your concern and prompt attention to
this matter.

**Comment by RatnadeepRoy01** [comment]
Great!
